### ISSUE TITLE
Add tags for the repo

### ISSUE THREAD

**Issue by farooqkz** [bigfoot547/rank#5]

**Comment by bigfoot547** [comment]
:+1: I can't add now, as I'm on an old computer lol

**Comment by farooqkz** [comment]
off topic, but where I can find you on IRC? `##temp`?what nick?
P.S.: they yold me you are coding an IRC bot and testing it there, I came to Github and your Minetest stuff was much better than your IRC bot :P

**Comment by bigfoot547** [comment]
@farooqkz on freenode, I can be found on ##temp with the same nick as on here :p
Also, thanks :)

**Comment by farooqkz** [comment]
ok ;)
